#!/usr/bin/env python
#
#  $Id: synopsis,v 1.21 2001/01/22 17:06:15 stefan Exp $
#
#  This file is a part of Synopsis.
#  Copyright (C) 2000, 2001 Stefan Seefeld
#
#  Synopsis is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
#  02111-1307, USA.

import sys, getopt, os, os.path, string
import cPickle

# Hack, I can't be stuffed finding places to change it :)
pickle = cPickle

from Synopsis.Core import Type, AST, Util

def version(): print "synopsis version 0.2"
cmdname = os.path.basename(sys.argv[0])
def usage():
    print "\nUsage:", cmdname, "[flags] files"
    print """
The supported flags are:

  -p,   --parser <parser>              Select a parser
  -Wp,<arg>[,<arg>...]                 Send args to the parser
  -Wl,<arg>[,<arg>...]                 Send args to the linker
  -f,   --formatter <formatter>        Select a formatter
  -Wf,<arg>[,<arg>...]                 Send args to the formatter
  -I<path>                             Specify include path
  -D<macro>                            Specify macro for the parser
  -o <file>                            Write output <file>
  -v,   --verbose                      Print debugging info
  -V,   --version                      Print version info then exit
  -h,   --help                         Print this usage message and exit

Linker options:
  -s <Scope>                           Link only the named scope.
                                       May be used multiple times.
		                       Default is to link all input.
		                       Eg: -Wl,-s,Prague,-s,Berlin::Console
  -m                                   Link only declarations in the main
				       files being processed.

HTML options:
    use -f HTML -Wf,-h  with valid input to see usage.

"""

parser_cmd = ""
parser_args = []
linker_cmd = "Linker"
linker_args = []
formatter_cmd = ""
formatter_args = []
output = ""
verbose = 0

def parseArgs(args):
    global parser_cmd, parser_args, linker_cmd, linker_args, formatter_cmd, formatter_args, output, verbose
    try:
        opts,files = Util.getopt_spec(args, "p:f:W:I:o:Vvh", ["parser=", "formatter=", "version", "help"])
    except getopt.error, e:
        sys.stderr.write("Error in arguments: " + e + "\n")
        sys.stderr.write("Use " + cmdname + " -h for help\n")
        sys.exit(1)

    for opt in opts:
        o,a = opt

        if o == "-p" or o == "--parser":
            parser_cmd = a

        elif o == "-f" or o == "--formatter":
            formatter_cmd = a

        elif o == "-W":
            if a[0] == "p":
                parser_args.extend(string.split(a[2:], ","))
            elif a[0] == "l":
                linker_args.extend(string.split(a[2:], ","))
            elif a[0] == "f":
                formatter_args.extend(string.split(a[2:], ","))
            else:
                sys.stderr.write("Error in arguments: option " + o + " not recognized\n")
                sys.stderr.write("Use " + cmdname + " -h for help\n")
                sys.exit(1)

        elif o == "-I":
            parser_args.append("-I" + a)
        elif o == "-D":
            parser_args.append("-D" + a)
        elif o == "-o":
            output = a
        elif o == "-v" or o == "--verbose":
            verbose = 1
        elif o == "-V" or o == "--version":
            version()
            sys.exit(0)
        elif o == "-h" or o == "--help":
            usage()
            sys.exit(0)

    return files

def main(argv=None):
    global parser_cmd, parser_args, linker_cmd, linker_args, formatter_cmd, formatter_args

    if argv is None: argv = sys.argv

    #
    # parse command line arguments
    #
    files = parseArgs(argv[1:])
    if len(files) == 0:
        sys.stderr.write(cmdname + ": No files specified\n")
        sys.exit(1)

    types = Type.Dictionary()
    declarations = []

    if parser_cmd != "":
        try:
            parser = Util._import("Synopsis.Parser." + parser_cmd)
        except ImportError:
            sys.stderr.write(cmdname + ": Could not import parser `" + parser_cmd + "'\n")
            raise#sys.exit(1)

    #
    # read files, either from picled data base or from parser
    #
    for file in files:
        if file != "-" and not os.path.isfile(file):
            sys.stderr.write(cmdname + ": `" + file + "' does not exist\n")
            sys.exit(1)

        if parser_cmd == "":
            if verbose: print "Loading pickled data from",file
            unpickler = pickle.Unpickler(open(file, "r"))
            try:
                t = unpickler.load()
                d = unpickler.load()
            except EOFError, e:
                break
            types.merge(t)
            declarations.extend(d)

        else:
            if verbose: print "*** Synopsis: Parsing"
            parser.parse(file, parser_args, types, declarations)

    #
    # resolve symbols here...
    if verbose: print "*** Synopsis: Linking"
    linker = Util._import("Synopsis.Linker." + linker_cmd)
    linker.resolve(linker_args, types, declarations)

    #
    # generate output, either with pickler or with a formatter
    #
    if formatter_cmd == "":
        if verbose: print "*** Synopsis: Writing file"
        if output == "":
            sys.stderr.write(cmdname + ": no output file specified\n")
            sys.exit(1)
	dir = os.path.split(output)[0]
	if dir and not os.path.exists(dir):
	    if verbose: print "Warning: Creating directory",dir
	    os.makedirs(dir, 0755)
        pickler = pickle.Pickler(open(output, "w"), 1)
        pickler.dump(types)
        pickler.dump(declarations)

    else:
        try:
            formatter = Util._import("Synopsis.Formatter." + formatter_cmd)
        except ImportError:
            sys.stderr.write(cmdname + ": Could not import formatter `" + formatter_cmd + "'\n")
            sys.exit(1)

        if output != "": formatter_args.extend(["-o",output])
        formatter.format(types, declarations, formatter_args)

if __name__ == '__main__':
        main()

