// This file is typically generated by an IDL to C++ translator.

namespace Storage
{
  class ObjectState;
  typedef ObjectState* ObjectState_ptr;
  typedef ObjectState_ptr ObjectStateRef;
  class ObjectState_var;
  class ObjectState_out;

  class Storable;
  typedef Storable* Storable_ptr;
  typedef Storable_ptr StorableRef;
  class Storable_var;
  class Storable_out;

  class Factory;
  typedef Factory* Factory_ptr;
  typedef Factory_ptr FactoryRef;
  class Factory_var;
  class Factory_out;
}

namespace POA_Storage
{

  class Storable;
  class Factory;
}

namespace OBV_Storage
{

}
