
interface Stream;

interface Alpha {
    attribute string name;
    attribute string comment;

    string add_comment(in string text);
    string print(out Stream print_to);
};

interface BetaAlpha : Alpha {
    attribute string authors;
    
    void add_author(in string author);
};
    
