.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Synopsis 1 "20010410"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
synopsis \- Source code documentation tool
.SH SYNOPSIS
.B synopsis
.RI [ options ]\ < input\ files >\ ...
.SH DESCRIPTION
This manual page documents briefly the
.B synopsis
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B synopsis
is a modular source code documentation tool with
support for a variety of programming languages, output formats,
and comment styles.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
help
.TP
.B \-V, \-\-version
print version info and exit
.TP
.B \-v, \-\-verbose
operate verbosely
.TP
.B \-d, \-\-debug
operate in debug mode
.TP
.B \-o, \-\-output
output file / directory
.TP
.B \-p, \-\-parser
select a parser
.TP
.B \-Wp,<arg>[,<arg>...]
send args to the parser
.TP
.B \-l, \-\-linker
link
.TP
.B \-Wl,<arg>[,<arg>...]
send args to the linker
.TP
.B \-f, \-\-formatter
select a formatter
.TP
.B \-Wf,<arg>[,<arg>...]
send args to the formatter
.TP
.B \-I <path>
specify include path
.TP
.B \-D <macro>
specify macro for the parser
.br
.TP
.B \-j, \-\-javadoc
process javadoc tags in comments
.\".SH SEE ALSO
.\".BR bar (1),
.\".BR baz (1).
.br
.SH AUTHOR
This manual page was written by Patrick Mauritz <oxygene@gmx.net>,
for the Debian GNU/Linux system (but may be used by others).
