const int a = 1 + 2 - 3;
const int b = 1 << 4;
const int c = 8 | 4, d = 22;
int e;
int f = e;
const int g = 1 > 2 ? 1 : 2;
const int h = (24 >> 3);
const int i = (-1);
const int j = ~0;
const bool k = true;
const bool l = false;
const unsigned int m = sizeof(int);
const unsigned int n = sizeof(char[8])/sizeof(char);
const unsigned int o = int(2 * sizeof(bool));
