#!/usr/bin/env python

"""
A minimal front end to the Docutils Publisher, producing HTML.
"""

try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import *
from docutils.frontend import *
from docutils.writers.html4css1 import HTMLTranslator, Writer

description = ('Generates (X)HTML documents from standalone '
               'reStructuredText sources.  ' + default_description)

publish_cmdline(writer_name='html', description=description)
#document = publish_doctree('')
#print document
#document.settings = OptionParser([Writer()]).get_default_values()
#visitor = HTMLTranslator(document)
#document.walkabout(visitor)
