#ifndef Storage_idl_
#define Storage_idl_

module Storage
{

interface ObjectState;

interface Storable
{
  void store(in ObjectState state);
  void load(in ObjectState state);
};

interface _Factory
{
  Storable create_uninitialized();
};

};

#endif
