
// All include files from /usr/include on Sun Solaris 5.5.1 (for x86)

#include <aio.h>
#include <alloca.h>
#include <ar.h>
#include <archives.h>
#include <assert.h>
#include <cpio.h>
#include <crypt.h>
#include <ctype.h>
#include <deflt.h>
#include <demangle.h>
#include <devmgmt.h>
#include <dirent.h>
#include <dlfcn.h>
#include <elf.h>
#include <errno.h>
#include <eti.h>
#include <euc.h>
#include <fatal.h>
#include <fcntl.h>
#include <float.h>
#include <floatingpoint.h>
#include <fmtmsg.h>
#include <fnmatch.h>
#include <form.h>
#include <ftw.h>
#include <getwidth.h>
#include <glob.h>
#include <grp.h>
#include <iconv.h>
#include <ieeefp.h>
#include <kstat.h>
#include <kvm.h>
#include <langinfo.h>
#include <lastlog.h>
#include <libelf.h>
#include <libgen.h>
#include <libgenIO.h>
#include <libintl.h>
#include <libw.h>
#include <limits.h>
#include <linenum.h>
#include <link.h>
#include <listen.h>
#include <locale.h>
#include <macros.h>
#include <maillock.h>
#include <malloc.h>
#include <math.h>
#include <memory.h>
#include <mon.h>
#include <monetary.h>
#include <mp.h>
#include <mqueue.h>
#include <nan.h>
#include <ndbm.h>
#include <netconfig.h>
#include <netdb.h>
#include <netdir.h>
#include <nl_types.h>
#include <nlist.h>
#include <note.h>
#include <nss_common.h>
#include <nss_dbdefs.h>
#include <nss_netdir.h>
#include <nsswitch.h>
#include <panel.h>
#include <pkgdev.h>
#include <pkginfo.h>
#include <pkglocs.h>
#include <pkgtrans.h>
#include <poll.h>
#include <proc_service.h>
#include <prof.h>
#include <pthread.h>
#include <pw.h>
#include <pwd.h>
#include <re_comp.h>
#include <regex.h>
#include <regexpr.h>
#include <resolv.h>
#include <rje.h>
#include <rmmount.h>
#include <rtld_db.h>
#include <sac.h>
#include <sched.h>
#include <search.h>
#include <semaphore.h>
#include <setjmp.h>
#include <shadow.h>
#include <siginfo.h>
#include <signal.h>
#include <std.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <storclass.h>
#include <string.h>
#include <strings.h>
#include <stropts.h>
#include <sum.h>
#include <syms.h>
#include <synch.h>
#include <sysexits.h>
#include <syslog.h>
#include <table.h>
#include <tar.h>
#include <term.h>
#include <termio.h>
#include <termios.h>
#include <thread.h>
#include <thread_db.h>
#include <time.h>
#include <tiuser.h>
#include <tzfile.h>
#include <ucontext.h>
#include <ulimit.h>
#include <unctrl.h>
#include <unistd.h>
#include <userdefs.h>
#include <ustat.h>
#include <utime.h>
#include <utmp.h>
#include <utmpx.h>
#include <valtools.h>
#include <values.h>
#include <varargs.h>
#include <volmgt.h>
#include <wait.h>
#include <wchar.h>
#include <wctype.h>
#include <widec.h>
#include <wordexp.h>

