\input texinfo @c -*-texinfo-*-
@setfilename GapBuffer.info
@settitle GapBuffer Manual

@c header for the info version
@ifinfo
manual for GapBuffer.

Copyright @copyright{} 2001 Stefan Seefeld

Permission is granted to make and distribute verbatim copies of this
document provided the copyright notice and this permission notice
are preserved on all copies.
@end ifinfo

@c title page for the printed version
@titlepage
@title GapBuffer class
@subtitle Version: xxxxxx
@author Stefan Seefeld

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2001 Stefan Seefeld

@sp 2
This is Version: xxxxxx of the GapBuffer class
@sp 2

Permission is granted to make and distribute verbatim copies of this
document provided the copyright notice and this permission notice
are preserved on all copies.
@end titlepage

@c top level menu
@ifinfo
@node Top, Copying, (dir), (dir)
@top GapBuffer

This is a sample document to demonstrate synopsis' texinfo generation capabilities
@end ifinfo

@menu
* Copying:: this demo is freely redistributable.
* Overview:: how does it work

@end menu

@include GapBuffer.texi

@contents
@bye
